/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param result при удачном исполнении запроса содержит OK
 * @param data массив объектов ResponseChat
 */
case class InlineResponse2002 (
  result: Option[String] = None,
  data: Option[List[ResponseChat]] = None
)

