/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param mimetype Mime type of file
 * @param data Base64 encoded data file body
 * @param filename Name of the file
 */
case class Media (
  mimetype: String,
  data: String,
  filename: String
)

