/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param body 
 * @param quote 
 * @param `type` 
 * @param media 
 */
case class MessageMedia (
  body: Option[String] = None,
  quote: Option[String] = None,
  `type`: Option[String] = None,
  media: Option[media] = None
)

