/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param id Идентификатор контакта или группы в формате WhatsApp
 * @param name Имя контакта или группы
 * @param isGroup Является ли чат контактом или группой
 * @param isReadOnly Является ли чат ReadOnly
 * @param unreadCount Количество непрочитанных сообщений в чате
 * @param timestamp Время последней активночти в чате
 * @param pinned Является ли чат закрепленным
 * @param isMuted Выключен ли у чата звук
 * @param muteExpiration Время, оставшееся до включения звука
 * @param groupMetadata 
 */
case class ResponseChat (
  id: Option[String] = None,
  name: Option[String] = None,
  isGroup: Option[Boolean] = None,
  isReadOnly: Option[Boolean] = None,
  unreadCount: Option[Integer] = None,
  timestamp: Option[Integer] = None,
  pinned: Option[Boolean] = None,
  isMuted: Option[Boolean] = None,
  muteExpiration: Option[Boolean] = None,
  groupMetadata: Option[ResponseChat_groupMetadata] = None
)

