/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * Метаданные группы, если чат является группой
 *
 * @param id Идентификатор группы в формате WhatsApp
 * @param creation Дата создания группы в формате Unix Time Stamp
 * @param owner Идентификатор создателя группы в формате WhatsApp
 * @param size Количество участников в группе
 * @param participants Массив участников
 */
case class ResponseChatGroupMetadata (
  id: Option[String] = None,
  creation: Option[Integer] = None,
  owner: Option[String] = None,
  size: Option[Integer] = None,
  participants: Option[List[ResponseChat_groupMetadata_participants]] = None
)

