/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param id Идентификатор контакта в формате WhatsApp
 * @param isAdmin Является ли участник администратором
 * @param isSuperAdmin Является ли участник суперадминистратором
 */
case class ResponseChatGroupMetadataParticipants (
  id: Option[String] = None,
  isAdmin: Option[Boolean] = None,
  isSuperAdmin: Option[Boolean] = None
)

