/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param id Идентификатор сообщения
 * @param ack Флаг просмотра сообщения
 * @param hasMedia Флаг, имеет ли сообщение медиафайл
 * @param mediaKey Ключ медиафайла (при наличии)
 * @param body Текст сообщения
 * @param `type` Тип сообщения
 * @param timestamp Время сообщения в формате Unix Timestamp
 * @param from Идентификатор отправителя в формате WhatsApp
 * @param to Идентификатор получателя в формате WhatsApp
 * @param isForwarded Флаг, было ли сообщение перенаправлено
 */
case class ResponseMessage (
  id: Option[String] = None,
  ack: Option[Integer] = None,
  hasMedia: Option[Boolean] = None,
  mediaKey: Option[String] = None,
  body: Option[String] = None,
  `type`: Option[String] = None,
  timestamp: Option[Integer] = None,
  from: Option[String] = None,
  to: Option[String] = None,
  isForwarded: Option[Boolean] = None
)

