/**
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param whatsappID Service Whatsapp ID
 * @param async Async query returns Message Object
 * @param recipient 
 * @param message 
 */
case class SendBody (
  whatsappID: String,
  async: Option[Boolean] = None,
  recipient: Option[AnyOfsendBodyRecipient] = None,
  message: Option[AnyOfsendBodyMessage] = None
)

